### ISSUE TITLE
Build Error on Docker Machine

### ISSUE THREAD

**Issue by mfigurski80** [akotlar/bystro#56]
I'm using docker-machine on a Windows 10. Trying to build from Dockerfile with `docker build -t bystro .` :: script exits with exit code 127 (command not found) when running install/install-go-packages.sh. Additionally, script creates similar warnings when installing lmdb, but does not exit.

This is my terminal output (at step 11):
```
Step 11/13 : RUN . install/install-go-packages.sh
 ---> Running in 7700bf77c2b1
: not found install/install-go-packages.sh:
-e

Installing go packages (bystro-vcf, stats, snp)

: not found install/install-go-packages.sh:
: not found install/install-go-packages.sh:
: not found install/install-go-packages.sh:
Made /root/go path
: not found install/install-go-packages.sh:
: not found install/install-go-packages.sh:
: not found: install/install-go-packages.sh:
: not found: install/install-go-packages.sh:
: not found: install/install-go-packages.sh:
: not found: install/install-go-packages.sh:
: not found: install/install-go-packages.sh:
: not found: install/install-go-packages.sh:
The command '/bin/sh -c . install/install-go-packages.sh' returned a non-zero code: 127
```

Note, the script does run when I run it manually through the console.

The error is likely caused by my use of docker machine. The default vm that docker-machine creates does **not** have go installed, and it does fail to execute the script with exit code 127.

**Comment by akotlar** [comment]
Where are you installing from? Try cd'ing into the bystro dir. Note `install/install-go-packages.sh` isn't found. This is clearly present in the cloned dir: https://github.com/akotlar/bystro/tree/b10/install

**Comment by mfigurski80** [comment]
I am indeed in the bystro directory while building: 

```
Step 11/13 : RUN . install/install-go-packages.sh
 ---> Running in 7700bf77c2b1
: not found install/install-go-packages.sh:
-e

Installing go packages (bystro-vcf, stats, snp)

: not found install/install-go-packages.sh:
: not found install/install-go-packages.sh:
: not found install/install-go-packages.sh:
Made /root/go path
: not found install/install-go-packages.sh:
: not found install/install-go-packages.sh:
: not found: install/install-go-packages.sh:
: not found: install/install-go-packages.sh:
: not found: install/install-go-packages.sh:
: not found: install/install-go-packages.sh:
: not found: install/install-go-packages.sh:
: not found: install/install-go-packages.sh:
The command '/bin/sh -c . install/install-go-packages.sh' returned a non-zero code: 127

mikof@DESKTOP-T2JVT0S MINGW64 ~/Documents/WINGO/docker/bystro (b10)
$ pwd
/c/Users/mikof/Documents/WINGO/docker/bystro
```

**Comment by akotlar** [comment]
You did say that. Ok. I don't understand why Go wouldn't exist; it should be installed before than install-go-packages.sh RUN command: https://github.com/akotlar/bystro/blob/b10/Dockerfile#L13 . Something slightly weird is happening

**Comment by mfigurski80** [comment]
Just an update: `install/install-go-packages.sh` as well as `install/install-lmdb-linux.sh`, which also had 'not-found' errors, are indeed in place at runtime.

```
Step 9/15 : RUN ls install/
 ---> Running in 0f0ad051b009
export-bystro-libs.sh
export-go-path-linux.sh
install-apt-deps.sh
install-go-linux.sh
install-go-mac.sh
install-go-packages.sh
install-liftover-linux.sh
install-lmdb-linux.sh
install-mac-deps.sh
install-perl-libs.sh
install-perlbrew-linux.sh
install-rpm-deps.sh
update-packages.sh
```

Additionally, go IS installed at runtime
```
Step 12/15 : RUN go version
 ---> Running in b8b9d08ef9c3
go version go1.11 linux/amd64
```

**Comment by mfigurski80** [comment]
Solved: Running on windows, the DOS carriage returns get messed up on the two shell scripts. They should be converted to Unix before building. Following commands should do it:

`awk '{ sub("\r$", ""); print }' install/install-lmdb-linux.sh > install/install-lmdb-linux.sh`, `awk '{ sub("\r$", ""); print }' install/install-go-packages.sh > install/install-go-packages.sh

**Comment by akotlar** [comment]
Awesome work!

**Comment by akotlar** [comment]
Oh wait...wtf. Why are \r present at all?

**Comment by akotlar** [comment]
I think git auto-converts line endings.

Could you propose, PR an update to documentation to make sure LF line endings are preserved on clone? 

Some proposals: https://github.com/LibreTime/libretime/issues/141

**Comment by mfigurski80** [comment]
PR sent: #57 

Tested on local machine: all files that need to be LF now stay that way after clone.
